#!/usr/bin/env python3

import click
import lib.Synthesis
import lib.Flash

@click.group()
def cli():
    print("WebFPGA CLI v0.1")

@cli.command()
def synth():
    """Synthesize one or more input Verilog files and save the bitstream"""
    click.echo('Synth')

@cli.command()
def flash():
    """Flash the first connected WebFPGA device"""
    click.echo('Flash')

cli()
